Backend for friends routes
hatchways/team-pumpkin pull request #43
Opened 2020-10-19 15:11 UTC by SsaaaadD2

What it does
- Added backend routes to add or remove friends
- Routes to make, cancel and reject friend requests
- Suggested friends: returns 20 random users from the database
- Route to return all the friends for a user
- Routes to see all requests made by a user and all requests received by a user

What to look for
server/friends/friend.js

2020-10-20 15:58 UTC, aeciorc requested changes
This looks good, but to keep the API cleaner, let's use the RESTful naming convention for routes. https://restfulapi.net/resource-naming/
For example, /friendRequests POST to create a friend request, DELETE to remove it 
/friends POST to accept an invitation and add a friend, DELETE to remove a friend

Doesn't have to be exactly like this, but something along these lines

2020-10-20 18:00 UTC, TheAllen reviewed
The routes look good to me. I think Aecio mention the better naming conventions for the routes. The jwtSign function that include the expireTime should be the right jwtSign function.

2020-10-20 18:00 UTC, TheAllen commented on server/routes/auth/register.js
> -      jwtSign(payload, process.env.JWT_SECRET, 1.577e7, res, userObject);
The jwtSign function with the time parameter is the correct jwtSign function

2020-10-20 18:00 UTC, TheAllen commented on server/routes/auth/signin.js
> -      jwtSign(payload, process.env.JWT_SECRET, 1.577e7, res, userObject);
Same here

2020-10-20 19:48 UTC, SsaaaadD2 commented on server/routes/auth/register.js
> -      jwtSign(payload, process.env.JWT_SECRET, 1.577e7, res, userObject);
Okay, should be fixed now

2020-10-20 19:49 UTC, SsaaaadD2 commented
> This looks good, but to keep the API cleaner, let's use the RESTful naming convention for routes. https://restfulapi.net/resource-naming/
> For example, /friendRequests POST to create a friend request, DELETE to remove it
> /friends POST to accept an invitation and add a friend, DELETE to remove a friend
> 
> Doesn't have to be exactly like this, but something along these lines

Okay, I've updated the route names

2020-10-21 15:54 UTC, aeciorc reviewed
Left some suggestions on how to rename the routes to fit the convention and the name of your entities

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.post("/friend/:id", [authentication], async function (req, res) {
```suggestion
router.post("/friends, [authentication], async function (req, res) { 
```
With the friend_id coming from the body

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.delete("/friend/:id", [authentication], async function (req, res) {
```suggestion
router.delete("/friends/:id", [authentication], async function (req, res) {
```

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.post("/friend-request/:id", [authentication], async function (req, res) {
```suggestion
router.post("/outgoing-requests", [authentication], async function (req, res) {
```
with the friend_id coming from the body

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.delete("/friend-request/:id", [authentication], async function (
```suggestion
router.delete("/outgoing-requests/:id", [authentication], async function (
```

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.delete("/reject-friend-request/:id", [authentication], async function (
```suggestion
router.delete("/received-requests/:id", [authentication], async function (
```

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.get("/friend-requests-sent", [authentication], async function (
```suggestion
router.get("/outgoing-requests", [authentication], async function (
```

2020-10-21 15:54 UTC, aeciorc commented on server/routes/friends/friend.js
> +router.get("/friend-requests-received", [authentication], async function (
```suggestion
router.get("/received-requests", [authentication], async function (
```

2020-10-21 18:17 UTC, aeciorc approved these changes

2020-10-21 18:18 UTC, merged